### DISCUSSION TITLE
Bot only responds "I am sorry, I am unable to respond at the moment."

### DISCUSSION THREAD

**Discussion by Kitasan-Black-Home** [The0mikkel/ollama-discord-bot#5] [Q&A]
Good evening,

I may be attempting to call it wrong, however according to the .py file as well as the instructions all I should have to do is @ the bot and then ask a question.  When I do this all I receive is "I am sorry, I am unable to respond at the moment". Is there a separate way which I should be using?  I notice       
```
return response_message
    except Exception as e:
      logging.error('Error generating response: %s', e)
      return 'I am sorry, I am unable to respond at the moment.'

```
Is there a place to maybe see what error is being thrown?

**Comment by Kitasan-Black-Home** [comment]
Also, I am using the model tinydolphin.  I did declare that in the .env but not sure if maybe that was supposed to be declared anywhere else?

**Reply by The0mikkel** [reply]
Is the ollama client running on thr machine, the docker container is running?
It required ollama to be accessible at a url to call - also try oprnwebui to test the model, which can also cause it

**Reply by Kitasan-Black-Home** [reply]
Good morning,

Yes, ollama serve is running, ollama pull tiny dolphin, changed OLLAMA_MODEL=tinydolphin, OLLAMA_HOST=0.0.0.0 (this is following Open WbUI's suggestion when you are running the bot on say a raspberrypi and accessing the webui from another machine).

**Reply by The0mikkel** [reply]
The host, if running the docker-compose.prod.yml file, should be: host.docker.internal

As this is how you access your machine that runs docker, and not just the docker container

**Reply by Kitasan-Black-Home** [reply]
I am running the docker-compose.yaml one.

```
version: '3'
services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    stop_grace_period: 1s
    env_file:
      - bot.env
    networks:
      - ollama
      - redis
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      redis:
        condition: service_healthy
      # ollama:
      #   condition: service_healthy
```
(left the redis portion out of the block here)
and the bot.env:

```
DISCORD_TOKEN=<token here>
ADMIN_ID=<id here>
CHAT_CHANNEL_ID=<channel id here>
#OLLAMA_HOST=0.0.0.0
OLLAMA_HOST=host.docker.internal
OLLAMA_PORT=11434
OLLAMA_MODEL=tinydolphin
REDIS_HOST=redis
BOT_NAME=RiceShower
CHAT_MAX_LENGTH=500
CTX=2048
```
This copy is with the 0.0.0.0 commented out.  I tried it both ways but the bot responded with "I am sorry, I am unable to respond at the moment."
